BASE:
  # log等级
  log_level: "debug"
  # 扩展名
  log_extension: ".log"
  test:
    url: "https://www.douyin.com"
    case_file: "testdata.xlsx"
    case_sheet: "美多商城接口测试"
email:
  smtpserver: "smtp.qq.com"
  username: "1490625639@qq.com"
  password: "faxxhfvbyvdtjbhh"
  receiver: "1490625639@qq.com"